// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBh_S_OjCKYGT9Gil4dgmcdMt6ms1Vtzk',
    appId: '1:660003224839:web:33e31082269f0e632c99a2',
    messagingSenderId: '660003224839',
    projectId: 'campus-events-planner',
    authDomain: 'campus-events-planner.firebaseapp.com',
    storageBucket: 'campus-events-planner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM8umaRVlKB8sVCySLK5lAAGcl7SDdi10',
    appId: '1:660003224839:android:84dae5de77fff3ab2c99a2',
    messagingSenderId: '660003224839',
    projectId: 'campus-events-planner',
    storageBucket: 'campus-events-planner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCihXVpiR5Bt20Zk6PrxZXBO8JgnQm2Tc',
    appId: '1:660003224839:ios:f4c89964aa70ed4e2c99a2',
    messagingSenderId: '660003224839',
    projectId: 'campus-events-planner',
    storageBucket: 'campus-events-planner.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCihXVpiR5Bt20Zk6PrxZXBO8JgnQm2Tc',
    appId: '1:660003224839:ios:f4c89964aa70ed4e2c99a2',
    messagingSenderId: '660003224839',
    projectId: 'campus-events-planner',
    storageBucket: 'campus-events-planner.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBh_S_OjCKYGT9Gil4dgmcdMt6ms1Vtzk',
    appId: '1:660003224839:web:8e66381692077f5d2c99a2',
    messagingSenderId: '660003224839',
    projectId: 'campus-events-planner',
    authDomain: 'campus-events-planner.firebaseapp.com',
    storageBucket: 'campus-events-planner.firebasestorage.app',
  );

}